$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

properties:
  workdir:
    type: string
    minLength: 1

  sample_name:
    type: string
    minLength: 1

  genome:
    type: string
    minLength: 1

  fastq:
    type: string
    minLength: 1

  aligner:
    type: string
    minLength: 1
    default: "minimap2"

  minimap2_opts:
    type: string

  ngmlr_opts:
    type: string

  sniffles_opts:
    type: string
  
  tandem_repeat_region:
    type: string

  straglr_opts:
    type: string

  threads:
    type: integer
    default: 30

required:
  - workdir
  - sample_name
  - genome
  - fastq
