# Set working directory
workdir: "/home/JHEmilGustavsson/MinaRyten/Emil/projects/FGF14/results" 

# prefix of all output files:
sample_name: "NB24"

# Reference genome as fasta
genome: "/home/MinaRyten/Emil/references/GRCh38.primary_assembly.genome.fa"

# Directory input data
fastq: "/home/JHEmilGustavsson/MinaRyten/Emil/projects/FGF14/barcode24/"

# Aligner to use (minimap2 or ngmlr; default: minimap2)
aligner: "minimap2"

# Options passed to minimap2 (optional)
minimap2_opts: ""

# Options passed to nglmr (optional)
ngmlr_opts: ""

# Options passed to sniffles
sniffles_opts: "--minsvlen 50 --tandem-repeats"

# Sniffles2 supports optionally specifying tandem repeat region annotations (.bed) 
# Give location of .bed file below and add "--tandem-repeats" at the end of sniffles_opts above
tandem_repeat_region: "/home/MinaRyten/Emil/Snakemakes/long-read_SV_calling/data/human_GRCh38_no_alt_analysis_set.trf.bed"

# Options passed to straglr
# stragle has many options for TR calling: https://github.com/bcgsc/straglr
straglr_opts: ""

# threads (optional; default:30)
threads: 100