# Set working directory
workdir: "/home/JHEmilGustavsson/MinaRyten/Emil/projects/SCA4/results" 

# prefix of all output files:
sample_name: "17274"

# Reference genome as fasta
genome: "/home/MinaRyten/Emil/references/GRCh38.primary_assembly.genome.fa"

# Directory input data
fastq: "/home/MinaRyten/Emil/projects/SCA4/data/17274/"

# Aligner to use (minimap2 or ngmlr; default: minimap2)
aligner: "ngmlr"

# Options passed to minimap2 (optional)
minimap2_opts: ""

# Options passed to nglmr (optional)
ngmlr_opts: ""

# Options passed to sniffles
sniffles_opts: "--minsvlen 50"

# threads (optional; default:30)
threads: 100